# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir numpy pandas six scikit-learn

# Set the environment variable for Python to run in unbuffered mode
ENV PYTHONUNBUFFERED 1

# Expose any necessary ports
EXPOSE 80

# Define the command to run on container start
CMD ["python", "src/train.py"]
